# Generated by Django 5.2.4 on 2025-07-10 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='priority',
            name='color',
        ),
    ]
